import type { Exercise } from './types'

/**
 * FEATURES.md Feature 1 — 24 exercises (8 legs, 8 push, 8 pull), plus the
 * old vanilla-version bodyweight exercises kept as offline/no-equipment
 * fallbacks. `role: "main"` exercises are compound lifts picked first for
 * the daily workout; `role: "accessory"` exercises appear only as swaps or
 * as the third pick when equipment rules out mains.
 */
export const EXERCISES: Exercise[] = [
  // ───────────── LEGS ─────────────
  {
    id: 'leg_press', name: 'Leg Press', group: 'legs', pattern: 'squat', role: 'main', equip: 'machine', level: 1,
    muscles: 'Quads, glutes',
    how: 'Feet shoulder-width in the middle of the platform. Lower until your knees reach about 90°, then push through your whole foot.',
    avoid: 'Locking your knees at the top, or letting your lower back peel off the pad.',
    start: 'Empty sled or 10 kg per side.',
    bonusTip: 'Take 3 seconds to lower and pause 1 second at the bottom. Slower lowering creates more muscle-building tension without adding weight.',
    description: 'A machine push for your legs. Works quads and glutes.',
    setup: 'Sit with your back and hips flat against the pad. Feet shoulder-width, in the middle of the platform.',
    steps: [
      'Release the safety handles and hold the side grips.',
      'Bend your knees and lower the platform slowly until your knees reach about 90°.',
      'Push through your whole foot back to the start, stopping just before your knees lock.',
    ],
    breathing: 'Breathe in as you lower, breathe out as you push.',
    feelIt: 'Front of your thighs and your glutes.',
    formCues: ['Lower back stays on the pad', 'Knees point the same way as your toes'],
  },
  {
    id: 'goblet_squat', name: 'Goblet Squat', group: 'legs', pattern: 'squat', role: 'main', equip: 'dumbbell', level: 1,
    muscles: 'Quads, glutes, core',
    how: 'Hold one dumbbell vertically against your chest. Sit down between your heels with your chest up, then stand tall.',
    avoid: 'Knees caving inward. Push them out in line with your toes.',
    start: 'One 6–10 kg dumbbell.',
    bonusTip: 'Pause for 2 seconds at the bottom of every rep. It removes the bounce so your legs do all the work, and it improves your squat depth.',
    description: 'A dumbbell squat held at your chest. Works quads, glutes and your core.',
    setup: 'Hold one dumbbell vertically against your chest with both hands, elbows pointing down. Feet just wider than shoulder-width.',
    steps: [
      'Brace your core and keep the dumbbell close to your chest.',
      'Sit down and back between your heels until your elbows brush your knees.',
      'Push through your heels and stand back up tall.',
    ],
    breathing: 'Breathe in as you sit down, breathe out as you stand.',
    feelIt: 'Front of your thighs, glutes, and your core staying braced.',
    formCues: ['Chest stays up, not leaning forward', 'Knees track out over your toes'],
  },
  {
    id: 'smith_squat', name: 'Smith Machine Squat', group: 'legs', pattern: 'squat', role: 'main', equip: 'machine', level: 2,
    muscles: 'Quads, glutes',
    how: 'Bar across your upper back, feet slightly in front of the bar. Sit down and back, then drive straight up.',
    avoid: 'Resting the bar on your neck, or rising onto your toes.',
    start: 'Empty bar.',
    bonusTip: 'Place your feet a little further forward to shift work to your glutes, or closer together to target your quads more.',
    description: 'A guided barbell squat on rails. Works quads and glutes.',
    setup: 'Step under the bar so it rests across your upper back, not your neck. Feet slightly in front of the bar, shoulder-width apart.',
    steps: [
      'Unrack the bar and twist to unlock it, then take a breath and brace.',
      'Sit down and back, keeping your weight through your whole foot, until your knees reach about 90°.',
      'Drive straight back up through your heels to standing.',
    ],
    breathing: 'Breathe in and brace before you sit down, breathe out as you drive up.',
    feelIt: 'Front of your thighs and your glutes.',
    formCues: ['Weight stays through your whole foot, not your toes', 'Knees track in line with your toes'],
  },
  {
    id: 'db_rdl', name: 'Dumbbell Romanian Deadlift', group: 'legs', pattern: 'hinge', role: 'main', equip: 'dumbbell', level: 2,
    muscles: 'Hamstrings, glutes, lower back',
    how: "Soft knees. Push your hips back and slide the dumbbells down your thighs until you feel a hamstring stretch, then squeeze your glutes to stand.",
    avoid: 'Rounding your back. Stop lowering where your flat back ends.',
    start: 'Two 6–10 kg dumbbells.',
    bonusTip: "Think 'hips back', not 'hands down'. The stretch in your hamstrings is where the growth happens, so control the lowering for 3 seconds.",
    description: 'A dumbbell hip hinge. Works your hamstrings, glutes and lower back.',
    setup: 'Stand tall holding a dumbbell in each hand in front of your thighs. Knees soft, not locked.',
    steps: [
      'Push your hips straight back, letting the dumbbells slide down the front of your thighs.',
      'Lower until you feel a stretch in your hamstrings, keeping your back flat.',
      'Squeeze your glutes to drive your hips forward and stand back up.',
    ],
    breathing: 'Breathe in as you push your hips back, breathe out as you stand.',
    feelIt: 'Back of your thighs (hamstrings) and your glutes.',
    formCues: ['Back stays flat, not rounded', 'Dumbbells stay close to your legs the whole way'],
  },
  {
    id: 'leg_curl', name: 'Seated Leg Curl', group: 'legs', pattern: 'hinge', role: 'accessory', equip: 'machine', level: 1,
    muscles: 'Hamstrings',
    how: 'Pad just above your heels, thigh pad snug. Curl down smoothly, pause, then let it return slowly.',
    avoid: 'Lifting your hips off the seat to swing the weight.',
    start: 'The lightest 2–3 plates on the stack.',
    bonusTip: 'Lean your torso slightly forward while curling. It stretches the hamstrings more and makes the same weight noticeably harder.',
    description: 'A machine curl for the back of your legs. Works your hamstrings.',
    setup: 'Sit or lie with the pad resting just above your heels and your hips flat against the seat.',
    steps: [
      'Curl your heels toward your glutes in a smooth, controlled motion.',
      'Pause for a moment at the top with your hamstrings fully squeezed.',
      "Let the weight return slowly to the start — don't let it drop.",
    ],
    breathing: 'Breathe out as you curl, breathe in as you return.',
    feelIt: 'Back of your thighs (hamstrings).',
    formCues: ['Hips stay flat on the seat the whole time', 'Movement is smooth, not jerky'],
  },
  {
    id: 'leg_extension', name: 'Leg Extension', group: 'legs', pattern: 'squat', role: 'accessory', equip: 'machine', level: 1,
    muscles: 'Quads',
    how: "Knees in line with the machine's pivot. Straighten your legs, squeeze for 1 second at the top, lower slowly.",
    avoid: 'Kicking the weight up with momentum.',
    start: 'The lightest 2–3 plates on the stack.',
    bonusTip: 'Hold the top position for a full 2 seconds on your last set. That squeeze gives a strong quad pump with very little joint stress.',
    description: 'A machine extension that isolates your quads.',
    setup: "Sit with your knees lined up with the machine's pivot point and the pad resting on the front of your ankles.",
    steps: [
      'Straighten your legs in a smooth, controlled motion.',
      'Pause and squeeze your quads for 1 second at the top.',
      'Lower slowly back to the start without letting the weight stack drop.',
    ],
    breathing: 'Breathe out as you straighten your legs, breathe in as you lower.',
    feelIt: 'Front of your thighs (quads).',
    formCues: ['Back stays against the seat', 'Movement is slow and controlled, not a kick'],
  },
  {
    id: 'db_lunge', name: 'Dumbbell Walking Lunge', group: 'legs', pattern: 'lunge', role: 'main', equip: 'dumbbell', level: 2,
    muscles: 'Quads, glutes',
    how: 'Dumbbells at your sides. Step forward, lower your back knee toward the floor, then push through the front heel into the next step.',
    avoid: 'Your front knee collapsing inward, or taking tiny steps.',
    start: 'Bodyweight first, then two 4–6 kg dumbbells.',
    bonusTip: 'Take a slightly longer stride and lean your torso forward a little to put more work into your glutes.',
    description: 'A walking lunge with dumbbells. Works your quads and glutes.',
    setup: 'Stand tall holding a dumbbell in each hand at your sides. Pick a clear stretch of floor to walk forward.',
    steps: [
      'Take a confident step forward and lower your back knee straight down toward the floor.',
      'Keep your front knee stacked over your ankle at the bottom.',
      'Push through your front heel to stand and step into the next lunge.',
    ],
    breathing: 'Breathe in as you step and lower, breathe out as you push up.',
    feelIt: 'Front thigh and glute of your leading leg.',
    formCues: ['Front knee stays over your ankle, not past your toes', 'Torso stays upright, not leaning forward'],
  },
  {
    id: 'hip_thrust', name: 'Barbell Hip Thrust', group: 'legs', pattern: 'hinge', role: 'main', equip: 'barbell', level: 2,
    muscles: 'Glutes, hamstrings',
    how: 'Upper back on a bench, padded bar across your hips. Drive your hips up until your body is flat from shoulders to knees, pause, lower.',
    avoid: 'Arching your lower back at the top. Keep your chin tucked and ribs down.',
    start: 'Empty bar with a pad.',
    bonusTip: 'Pause for 2 seconds at the top of each rep and squeeze your glutes hard. Tension at the top is what makes this exercise work.',
    description: 'A barbell hip drive. Works your glutes and hamstrings hard.',
    setup: 'Sit on the floor with your upper back against a bench and the padded bar rolled over your hips. Feet flat, knees bent.',
    steps: [
      'Plant your feet and brace your core.',
      'Drive your hips up until your body forms a straight line from shoulders to knees.',
      'Pause and squeeze your glutes, then lower with control back to the start.',
    ],
    breathing: 'Breathe in at the bottom, breathe out as you drive your hips up.',
    feelIt: 'Your glutes, mainly, with some hamstrings.',
    formCues: ['Chin stays tucked, ribs stay down at the top', 'Feet stay flat and under your knees'],
  },

  // ───────────── PUSH ─────────────
  {
    id: 'chest_press', name: 'Chest Press Machine', group: 'push', pattern: 'hpush', role: 'main', equip: 'machine', level: 1,
    muscles: 'Chest, front shoulders, triceps',
    how: 'Handles at mid-chest height. Press forward without locking your elbows, then return slowly until you feel a chest stretch.',
    avoid: 'Shoulders rolling forward off the pad.',
    start: '10–20 kg on the stack.',
    bonusTip: 'Pinch your shoulder blades together before the first rep and keep them there. Your chest does more of the work and your shoulders stay safer.',
    description: 'A machine push for your chest. Also works your shoulders and triceps.',
    setup: 'Sit with your back flat against the pad and the handles level with your mid-chest.',
    steps: [
      'Press the handles forward and together, without fully locking your elbows.',
      'Pause briefly at full extension.',
      'Return slowly until you feel a stretch across your chest.',
    ],
    breathing: 'Breathe out as you press, breathe in as you return.',
    feelIt: 'Chest, with your shoulders and triceps helping.',
    formCues: ['Shoulder blades stay pinned to the pad', 'Elbows stay just short of locking out'],
  },
  {
    id: 'db_bench', name: 'Dumbbell Bench Press', group: 'push', pattern: 'hpush', role: 'main', equip: 'dumbbell', level: 2,
    muscles: 'Chest, triceps, front shoulders',
    how: 'Lie on a flat bench, dumbbells above your chest. Lower to chest level with elbows at about 45°, then press up.',
    avoid: 'Flaring your elbows straight out to the sides.',
    start: 'Two 5–8 kg dumbbells.',
    bonusTip: 'Let the dumbbells go slightly deeper than a barbell would allow. That extra stretch at the bottom is a big driver of chest growth.',
    description: 'A dumbbell bench press. Works your chest, triceps and front shoulders.',
    setup: 'Lie flat on a bench with a dumbbell in each hand, held above your chest with straight arms.',
    steps: [
      'Lower the dumbbells together with your elbows at about 45° to your body.',
      'Touch (or come close to) chest level with control.',
      'Press the dumbbells back up and slightly together over your chest.',
    ],
    breathing: 'Breathe in as you lower, breathe out as you press.',
    feelIt: 'Chest, with your triceps and front shoulders helping.',
    formCues: ['Elbows stay at about 45°, not flared to the sides', 'Feet stay flat on the floor for stability'],
  },
  {
    id: 'incline_db', name: 'Incline Dumbbell Press', group: 'push', pattern: 'hpush', role: 'main', equip: 'dumbbell', level: 2,
    muscles: 'Upper chest, front shoulders',
    how: 'Bench at a low incline (about 30°). Lower the dumbbells to upper-chest level, press up and slightly together.',
    avoid: 'Setting the bench too steep, which turns it into a shoulder press.',
    start: 'Two 4–7 kg dumbbells.',
    bonusTip: 'Keep the incline low, around 30°. It targets the upper chest better than steeper angles, which shift the work to your shoulders.',
    description: 'A dumbbell press on an incline. Works your upper chest and front shoulders.',
    setup: 'Set the bench to a low incline, about 30°. Lie back with a dumbbell in each hand at upper-chest level.',
    steps: [
      'Press the dumbbells up until your arms are extended over your upper chest.',
      'Pause briefly at the top without locking out hard.',
      'Lower with control back to upper-chest level.',
    ],
    breathing: 'Breathe in as you lower, breathe out as you press.',
    feelIt: 'Upper chest and front shoulders.',
    formCues: ['Bench stays at a low angle, around 30°', 'Dumbbells come back to upper-chest level, not your neck'],
  },
  {
    id: 'pec_deck', name: 'Pec Deck Fly', group: 'push', pattern: 'hpush', role: 'accessory', equip: 'machine', level: 1,
    muscles: 'Chest',
    how: 'Handles at chest height, slight bend in your elbows. Bring your arms together in a hugging arc, squeeze, return slowly.',
    avoid: 'Letting the handles pull your arms far behind your body.',
    start: 'The lightest 2–3 plates on the stack.',
    bonusTip: 'Squeeze for 1 second where the handles meet, as if pushing your biceps together. That peak squeeze is what makes flies effective.',
    description: 'A machine chest fly that isolates your chest.',
    setup: 'Sit tall with your back against the pad and your forearms or hands on the handles at chest height.',
    steps: [
      'Bring your arms together in front of your chest in a hugging arc.',
      'Squeeze your chest for 1 second where the handles meet.',
      'Return slowly, letting your arms open only until you feel a light stretch.',
    ],
    breathing: 'Breathe out as you squeeze, breathe in as you open.',
    feelIt: 'Across your chest.',
    formCues: ['Slight bend stays in your elbows throughout', "Arms don't travel past a comfortable stretch behind you"],
  },
  {
    id: 'machine_shoulder', name: 'Shoulder Press Machine', group: 'push', pattern: 'vpush', role: 'main', equip: 'machine', level: 1,
    muscles: 'Shoulders, triceps',
    how: 'Handles at shoulder level. Press overhead without shrugging, lower with control.',
    avoid: 'Arching your back off the pad.',
    start: '5–15 kg on the stack.',
    bonusTip: 'Stop just short of locking out at the top. Keeping constant tension on your shoulders works them harder than resting at the top.',
    description: 'A machine overhead press. Works your shoulders and triceps.',
    setup: 'Sit with your back flat against the pad and the handles level with your shoulders.',
    steps: [
      'Press the handles straight up without shrugging your shoulders toward your ears.',
      'Pause just short of locking your elbows out.',
      'Lower with control back to shoulder level.',
    ],
    breathing: 'Breathe out as you press up, breathe in as you lower.',
    feelIt: 'Top of your shoulders and your triceps.',
    formCues: ['Back stays flat against the pad', 'Shoulders stay down, away from your ears'],
  },
  {
    id: 'db_shoulder', name: 'Seated Dumbbell Shoulder Press', group: 'push', pattern: 'vpush', role: 'main', equip: 'dumbbell', level: 1,
    muscles: 'Shoulders, triceps',
    how: 'Sit upright with back support. Press the dumbbells overhead, lower to ear level.',
    avoid: 'The dumbbells drifting forward in front of your face.',
    start: 'Two 4–6 kg dumbbells.',
    bonusTip: "Turn your palms slightly inward, around 30°. It's easier on the shoulder joint and usually lets you press more weight with good form.",
    description: 'A seated dumbbell overhead press. Works your shoulders and triceps.',
    setup: 'Sit upright with back support, a dumbbell in each hand at ear level, palms facing forward.',
    steps: [
      'Press both dumbbells straight overhead.',
      'Pause just short of locking your elbows at the top.',
      'Lower with control back to ear level.',
    ],
    breathing: 'Breathe out as you press, breathe in as you lower.',
    feelIt: 'Top of your shoulders and your triceps.',
    formCues: ['Dumbbells stay stacked over your elbows, not drifting forward', 'Lower back stays against the seat'],
  },
  {
    id: 'lateral_raise', name: 'Dumbbell Lateral Raise', group: 'push', pattern: 'vpush', role: 'accessory', equip: 'dumbbell', level: 1,
    muscles: 'Side shoulders',
    how: 'Slight bend in your elbows. Raise your arms out to the sides up to shoulder height, lower slowly.',
    avoid: 'Swinging. If you need momentum, the weight is too heavy.',
    start: 'Two 2–4 kg dumbbells. Lighter than you think.',
    bonusTip: 'Lead with your elbows, not your hands, and lean forward slightly. This isolates the side shoulder, which gives you wider-looking shoulders.',
    description: 'A dumbbell side raise that isolates your side shoulders.',
    setup: 'Stand tall with a light dumbbell in each hand at your sides, a slight bend in your elbows.',
    steps: [
      'Raise both arms out to the sides, leading with your elbows.',
      'Stop at shoulder height — no higher.',
      'Lower slowly back to your sides.',
    ],
    breathing: 'Breathe out as you raise, breathe in as you lower.',
    feelIt: 'Side of your shoulders.',
    formCues: ['Arms stay just at or below shoulder height at the top', 'Movement stays slow — no swinging'],
  },
  {
    id: 'triceps_pushdown', name: 'Cable Triceps Pushdown', group: 'push', pattern: 'arms', role: 'accessory', equip: 'cable', level: 1,
    muscles: 'Triceps',
    how: 'Elbows pinned to your sides. Push the bar or rope down until your arms are straight, return until your forearms are just above parallel.',
    avoid: 'Elbows drifting forward, or leaning your bodyweight onto the bar.',
    start: '10–15 kg on the stack.',
    bonusTip: 'Use the rope and spread it apart at the bottom. The extra squeeze fully contracts the triceps.',
    description: 'A cable pushdown that isolates your triceps.',
    setup: 'Stand tall facing the cable, elbows pinned to your sides, hands on the bar or rope at chest height.',
    steps: [
      'Push the bar or rope down until your arms are fully straight.',
      'Pause and squeeze your triceps at the bottom.',
      'Return with control until your forearms are just above parallel to the floor.',
    ],
    breathing: 'Breathe out as you push down, breathe in as you return.',
    feelIt: 'Back of your upper arms (triceps).',
    formCues: ['Elbows stay pinned to your sides the whole time', 'Upper body stays upright, not leaning into the bar'],
  },

  // ───────────── PULL ─────────────
  {
    id: 'lat_pulldown', name: 'Lat Pulldown', group: 'pull', pattern: 'vpull', role: 'main', equip: 'cable', level: 1,
    muscles: 'Lats, biceps',
    how: 'Grip a little wider than shoulders. Pull the bar to your upper chest by driving your elbows down, return slowly to a full stretch.',
    avoid: 'Leaning far back or pulling the bar behind your neck.',
    start: '15–25 kg on the stack.',
    bonusTip: "Imagine pulling with your elbows, not your hands. Thinking 'elbows to back pockets' makes your back work instead of your biceps.",
    description: 'A cable pulldown for your back. Works your lats and biceps.',
    setup: 'Sit with your thighs secured under the pad, hands gripping the bar a little wider than shoulder-width.',
    steps: [
      'Pull the bar down to your upper chest by driving your elbows down and back.',
      'Pause and squeeze your shoulder blades together.',
      'Return slowly to a full stretch at the top.',
    ],
    breathing: 'Breathe out as you pull down, breathe in as you return.',
    feelIt: 'Your back (lats), with your biceps helping.',
    formCues: ['Torso stays mostly upright, not leaning far back', 'Bar comes to your upper chest, not behind your neck'],
  },
  {
    id: 'assisted_pullup', name: 'Assisted Pull-up Machine', group: 'pull', pattern: 'vpull', role: 'main', equip: 'machine', level: 1,
    muscles: 'Lats, biceps, upper back',
    how: 'Kneel on the pad. Pull your chest toward the bar, then lower all the way down.',
    avoid: 'Too little assistance. More assist weight makes it easier.',
    start: 'High assistance, 30–40 kg.',
    bonusTip: "Reduce the assistance by one plate whenever you hit the top of your rep range on every set. That's your path to an unassisted pull-up.",
    description: 'An assisted pull-up machine. Works your lats, biceps and upper back.',
    setup: 'Kneel or stand on the assist platform with your hands gripping the bar just wider than shoulder-width.',
    steps: [
      'Pull your chest up toward the bar, driving your elbows down.',
      'Pause briefly with your chest near the bar.',
      'Lower yourself all the way down to a full arm stretch.',
    ],
    breathing: 'Breathe out as you pull up, breathe in as you lower.',
    feelIt: 'Your back (lats) and biceps.',
    formCues: ['You lower all the way to a full stretch each rep', 'Shoulders stay down, away from your ears'],
  },
  {
    id: 'seated_row', name: 'Seated Cable Row', group: 'pull', pattern: 'hpull', role: 'main', equip: 'cable', level: 1,
    muscles: 'Mid back, lats, biceps',
    how: 'Sit tall, slight knee bend. Pull the handle to your belly button, squeeze your shoulder blades, return with a stretch.',
    avoid: 'Rocking your torso back and forth to move the weight.',
    start: '15–25 kg on the stack.',
    bonusTip: 'Let your shoulder blades stretch forward at the start of each rep, then squeeze them together at the end. The full range builds a thicker back.',
    description: 'A seated cable row. Works your mid back, lats and biceps.',
    setup: 'Sit tall with a slight bend in your knees, feet braced on the platform, holding the handle with arms extended.',
    steps: [
      'Pull the handle toward your belly button, driving your elbows back.',
      'Squeeze your shoulder blades together at the end.',
      'Return with control to a full stretch at the front.',
    ],
    breathing: 'Breathe out as you pull, breathe in as you return.',
    feelIt: 'Mid back, with your lats and biceps helping.',
    formCues: ['Torso stays tall, not rocking back and forth', 'Shoulder blades squeeze together at the finish'],
  },
  {
    id: 'machine_row', name: 'Chest-Supported Row Machine', group: 'pull', pattern: 'hpull', role: 'main', equip: 'machine', level: 1,
    muscles: 'Mid back, rear shoulders',
    how: 'Chest on the pad. Pull the handles back until your elbows pass your ribs, pause, return slowly.',
    avoid: 'Shrugging your shoulders up toward your ears.',
    start: '10–20 kg or one plate per side.',
    bonusTip: "Because your chest is supported, you can't cheat. Push close to failure on your final set to get the most from it safely.",
    description: 'A chest-supported row machine. Works your mid back and rear shoulders.',
    setup: 'Rest your chest against the pad and grip the handles with your arms extended.',
    steps: [
      'Pull the handles back until your elbows pass your ribs.',
      'Pause and squeeze your shoulder blades together.',
      'Return slowly to a full stretch at the front.',
    ],
    breathing: 'Breathe out as you pull, breathe in as you return.',
    feelIt: 'Mid back and rear shoulders.',
    formCues: ['Chest stays on the pad the whole set', 'Shoulders stay down, away from your ears'],
  },
  {
    id: 'db_row', name: 'One-Arm Dumbbell Row', group: 'pull', pattern: 'hpull', role: 'main', equip: 'dumbbell', level: 1,
    muscles: 'Lats, mid back, biceps',
    how: 'One hand and knee on a bench. Pull the dumbbell toward your hip, lower with a stretch.',
    avoid: 'Twisting your torso to heave the weight up.',
    start: 'One 8–12 kg dumbbell.',
    bonusTip: 'Pull toward your hip in an arc rather than straight up. This targets your lats more than your upper back.',
    description: 'A one-arm dumbbell row. Works your lats, mid back and biceps.',
    setup: 'Place one hand and knee on a bench for support, back flat, and hold the dumbbell in your other hand, arm extended.',
    steps: [
      'Pull the dumbbell up toward your hip, driving your elbow back.',
      'Pause and squeeze at the top.',
      'Lower with control to a full stretch.',
    ],
    breathing: 'Breathe out as you pull, breathe in as you lower.',
    feelIt: 'Your back (lats and mid back), with your biceps helping.',
    formCues: ['Back stays flat, not twisting toward the weight', 'Dumbbell travels in an arc toward your hip'],
  },
  {
    id: 'face_pull', name: 'Cable Face Pull', group: 'pull', pattern: 'hpull', role: 'accessory', equip: 'cable', level: 1,
    muscles: 'Rear shoulders, upper back',
    how: 'Rope at upper-chest height. Pull toward your face, separating the rope ends and rotating your hands back.',
    avoid: 'Using so much weight that you lean back to pull it.',
    start: '5–10 kg on the stack.',
    bonusTip: 'Finish each rep with your hands beside your ears, like a double-biceps pose. It builds rear shoulders and helps posture after desk work.',
    description: 'A cable face pull. Works your rear shoulders and upper back.',
    setup: 'Stand facing the cable with the rope set at upper-chest height, holding one end in each hand.',
    steps: [
      'Pull the rope toward your face, leading with your elbows high.',
      'Separate your hands and rotate them back as you pull.',
      'Return with control to a full stretch.',
    ],
    breathing: 'Breathe out as you pull, breathe in as you return.',
    feelIt: 'Rear shoulders and upper back.',
    formCues: ['Elbows stay high, level with your shoulders', 'Upper body stays still — no leaning back to pull'],
  },
  {
    id: 'db_curl', name: 'Dumbbell Biceps Curl', group: 'pull', pattern: 'arms', role: 'accessory', equip: 'dumbbell', level: 1,
    muscles: 'Biceps',
    how: 'Stand tall, elbows at your sides. Curl the dumbbells up while turning your palms up, lower slowly.',
    avoid: 'Swinging your body or letting your elbows drift forward.',
    start: 'Two 4–6 kg dumbbells.',
    bonusTip: 'Lower each rep over 3 seconds. Most beginners drop the weight quickly and miss half the benefit.',
    description: 'A dumbbell biceps curl.',
    setup: 'Stand tall with a dumbbell in each hand, arms extended, elbows close to your sides.',
    steps: [
      'Curl the dumbbells up while turning your palms to face up.',
      'Squeeze your biceps at the top.',
      'Lower slowly back to a full stretch.',
    ],
    breathing: 'Breathe out as you curl, breathe in as you lower.',
    feelIt: 'Front of your upper arms (biceps).',
    formCues: ['Elbows stay pinned to your sides', 'Body stays still — no swinging the weight up'],
  },
  {
    id: 'hammer_curl', name: 'Hammer Curl', group: 'pull', pattern: 'arms', role: 'accessory', equip: 'dumbbell', level: 1,
    muscles: 'Biceps, forearms',
    how: 'Palms facing each other throughout. Curl up, pause, lower slowly.',
    avoid: 'Rocking your torso to swing the weight.',
    start: 'Two 4–6 kg dumbbells.',
    bonusTip: 'Hammer curls work the muscle underneath the biceps, which makes your arms look thicker from the front.',
    description: 'A dumbbell curl with a neutral grip. Works your biceps and forearms.',
    setup: 'Stand tall with a dumbbell in each hand, palms facing each other, arms extended.',
    steps: [
      'Curl both dumbbells up, keeping your palms facing each other.',
      'Pause and squeeze at the top.',
      'Lower slowly back to a full stretch.',
    ],
    breathing: 'Breathe out as you curl, breathe in as you lower.',
    feelIt: 'Front of your upper arms and forearms.',
    formCues: ['Palms stay facing each other the whole rep', 'Elbows stay still — no rocking your torso to help'],
  },

  // ───────────── BODYWEIGHT FALLBACKS (ported from the vanilla version) ─────────────
  {
    id: 'box_squat', name: 'Bench Box Squat', group: 'legs', pattern: 'squat', role: 'main', equip: 'bodyweight', level: 1,
    muscles: 'Quads, glutes',
    how: 'Stand in front of a bench. Sit back until you lightly touch it, then stand up without rocking.',
    avoid: 'Flopping onto the bench — aim for a light tap and stand straight back up.',
    start: 'Bodyweight only. Add a dumbbell held at your chest once 15 reps feel easy.',
    bonusTip: 'Reach your arms straight out in front as you sit back. It counterbalances your weight and keeps your torso more upright.',
    description: 'A bodyweight squat to a bench. Works your quads and glutes.',
    setup: 'Stand in front of a sturdy bench with your feet shoulder-width apart, bench just behind your heels.',
    steps: [
      "Reach your arms out in front and sit back slowly, like you're aiming for the bench.",
      "Lightly tap the bench with your glutes — don't sit down fully.",
      'Stand back up without rocking or using your arms for momentum.',
    ],
    breathing: 'Breathe in as you sit back, breathe out as you stand.',
    feelIt: 'Front of your thighs and your glutes.',
    formCues: ['Only a light tap on the bench, not a full sit', 'Weight stays through your whole foot'],
  },
  {
    id: 'split_squat', name: 'Split Squat', group: 'legs', pattern: 'squat', role: 'accessory', equip: 'bodyweight', level: 2,
    muscles: 'Quads, glutes',
    how: 'One foot forward, one back. Drop your back knee straight down, then push up through the front heel.',
    avoid: 'Letting the front knee collapse inward.',
    start: 'Hold a wall or rack for balance at first; add dumbbells once steady.',
    bonusTip: 'Keep most of your weight on the front heel, not your toes. It shifts more work onto your glutes and protects your front knee.',
    description: 'A bodyweight split stance squat. Works your quads and glutes, one leg at a time.',
    setup: 'Stand in a split stance, one foot well forward and one well back. Hold a wall or rack for balance if you need it.',
    steps: [
      'Drop your back knee straight down toward the floor.',
      'Keep your front knee stacked over your ankle at the bottom.',
      'Push through your front heel to stand back up.',
    ],
    breathing: 'Breathe in as you lower, breathe out as you push up.',
    feelIt: 'Front thigh and glute of your front leg.',
    formCues: ['Front knee tracks over your ankle, not caving in', 'Most of your weight stays on your front heel'],
  },
  {
    id: 'glute_bridge', name: 'Glute Bridge', group: 'legs', pattern: 'hinge', role: 'main', equip: 'bodyweight', level: 1,
    muscles: 'Glutes, hamstrings',
    how: 'Lie on your back, knees bent, feet flat. Squeeze your glutes to lift your hips into a straight line, pause 1 second.',
    avoid: 'Arching your lower back at the top — keep your ribs down.',
    start: 'Bodyweight. Rest a dumbbell across your hips once it feels easy.',
    bonusTip: 'Pause 2 full seconds at the top of every rep. Bodyweight only gets harder if you add time under tension, not just reps.',
    description: 'A bodyweight hip raise. Works your glutes and hamstrings.',
    setup: 'Lie on your back with your knees bent and feet flat on the floor, close to your glutes.',
    steps: [
      'Squeeze your glutes and lift your hips up until your body forms a straight line from shoulders to knees.',
      'Pause for 1 second at the top.',
      'Lower with control back to the start.',
    ],
    breathing: 'Breathe out as you lift, breathe in as you lower.',
    feelIt: 'Your glutes, mainly, with some hamstrings.',
    formCues: ['Ribs stay down, not arching your lower back', 'Feet stay flat and close to your glutes'],
  },
  {
    id: 'incline_pushup', name: 'Incline Push-up', group: 'push', pattern: 'hpush', role: 'main', equip: 'bodyweight', level: 1,
    muscles: 'Chest, triceps',
    how: 'Hands on a bench or bar, body in a straight line. Lower your chest to the edge, then push away.',
    avoid: 'Letting your hips sag toward the floor.',
    start: 'Use a higher surface to start; lower the surface as you get stronger.',
    bonusTip: "Move to a lower surface (or the floor) as soon as 15 clean reps feel easy — that's the bodyweight version of adding weight.",
    description: 'A push-up with your hands raised. Works your chest and triceps.',
    setup: 'Place your hands on a sturdy bench or bar, a little wider than shoulder-width. Walk your feet back so your body forms a straight line.',
    steps: [
      'Brace your core and lower your chest toward the edge of the surface.',
      'Keep your elbows at about 45° to your body as you lower.',
      'Push away back to a straight-arm start.',
    ],
    breathing: 'Breathe in as you lower, breathe out as you push away.',
    feelIt: 'Chest, with your triceps helping.',
    formCues: ["Body stays in a straight line, hips don't sag", 'Elbows stay at about 45°, not flared straight out'],
  },
  {
    id: 'pike_pushup', name: 'Wall Shoulder Tap Hold', group: 'push', pattern: 'vpush', role: 'main', equip: 'bodyweight', level: 1,
    muscles: 'Shoulders, core',
    how: 'Hands on a wall at shoulder height, step back. Lean in and press away, keeping elbows at about 45°.',
    avoid: 'Letting your head drop forward as you lean in.',
    start: 'Bodyweight. Step farther from the wall to make it harder.',
    bonusTip: "Step your feet back an inch at a time. Distance from the wall is your only 'weight' here, so add it gradually.",
    description: 'A wall-supported press. Works your shoulders and core.',
    setup: 'Stand facing a wall, hands on it at shoulder height, and step your feet back until you feel a lean.',
    steps: [
      'Bend your elbows and lean your body in toward the wall.',
      'Keep your elbows at about 45° to your body as you lean.',
      'Press away back to the start.',
    ],
    breathing: 'Breathe in as you lean in, breathe out as you press away.',
    feelIt: 'Shoulders, with your core working to stay braced.',
    formCues: ['Head stays in line with your spine, not dropping forward', 'Body stays straight, not bending at the hips'],
  },
  {
    id: 'prone_y', name: 'Prone Y-Raise', group: 'pull', pattern: 'vpull', role: 'main', equip: 'bodyweight', level: 1,
    muscles: 'Upper back, rear shoulders',
    how: 'Lie face-down, arms overhead in a Y shape. Lift your arms by squeezing your shoulder blades, pause, lower.',
    avoid: 'Lifting with your neck — keep your eyes on the floor.',
    start: 'Bodyweight. Very light plates in each hand once easy.',
    bonusTip: 'Squeeze your shoulder blades together before your arms even move. That\'s the muscle this exercise is training.',
    description: 'A face-down raise. Works your upper back and rear shoulders.',
    setup: 'Lie face down with your arms stretched overhead in a wide Y shape, thumbs pointing up.',
    steps: [
      'Squeeze your shoulder blades together and lift your arms a few inches off the floor.',
      'Pause briefly at the top.',
      'Lower with control back to the start.',
    ],
    breathing: 'Breathe out as you lift, breathe in as you lower.',
    feelIt: 'Upper back and rear shoulders.',
    formCues: ['Eyes stay on the floor, not lifting with your neck', 'Movement comes from your shoulder blades, not your arms swinging'],
  },
  {
    id: 'snow_angel', name: 'Reverse Snow Angel', group: 'pull', pattern: 'hpull', role: 'main', equip: 'bodyweight', level: 1,
    muscles: 'Upper back',
    how: 'Lie face-down, arms at your sides. Lift your arms slightly and sweep them overhead and back, like a snow angel.',
    avoid: 'Rushing the movement — slow and controlled is the point.',
    start: 'Bodyweight.',
    bonusTip: 'Keep your chin gently tucked throughout. It stops your neck from doing the work your upper back should be doing.',
    description: 'A face-down sweeping raise. Works your upper back.',
    setup: 'Lie face down with your arms at your sides, palms facing down.',
    steps: [
      'Lift your arms slightly off the floor.',
      'Sweep them out and overhead in a wide arc, like making a snow angel.',
      'Reverse the arc back to your sides with control.',
    ],
    breathing: 'Breathe out as you sweep up, breathe in as you return.',
    feelIt: 'Upper back, between your shoulder blades.',
    formCues: ['Movement stays slow and controlled, not rushed', 'Arms stay just off the floor throughout'],
  },
]

export const BY_ID: Record<string, Exercise> = Object.fromEntries(EXERCISES.map((e) => [e.id, e]))
