import type { Exercise } from './types'

/**
 * FEATURES.md Feature 1 — 24 exercises (8 legs, 8 push, 8 pull), plus the
 * old vanilla-version bodyweight exercises kept as offline/no-equipment
 * fallbacks. `role: "main"` exercises are compound lifts picked first for
 * the daily workout; `role: "accessory"` exercises appear only as swaps or
 * as the third pick when equipment rules out mains.
 */
export const EXERCISES: Exercise[] = [
  // ───────────── LEGS ─────────────
  {
    id: 'leg_press', name: 'Leg Press', group: 'legs', pattern: 'squat', role: 'main', equip: 'machine', level: 1,
    muscles: 'Quads, glutes',
    how: 'Feet shoulder-width in the middle of the platform. Lower until your knees reach about 90°, then push through your whole foot.',
    avoid: 'Locking your knees at the top, or letting your lower back peel off the pad.',
    start: 'Empty sled or 10 kg per side.',
    bonusTip: 'Take 3 seconds to lower and pause 1 second at the bottom. Slower lowering creates more muscle-building tension without adding weight.',
  },
  {
    id: 'goblet_squat', name: 'Goblet Squat', group: 'legs', pattern: 'squat', role: 'main', equip: 'dumbbell', level: 1,
    muscles: 'Quads, glutes, core',
    how: 'Hold one dumbbell vertically against your chest. Sit down between your heels with your chest up, then stand tall.',
    avoid: 'Knees caving inward. Push them out in line with your toes.',
    start: 'One 6–10 kg dumbbell.',
    bonusTip: 'Pause for 2 seconds at the bottom of every rep. It removes the bounce so your legs do all the work, and it improves your squat depth.',
  },
  {
    id: 'smith_squat', name: 'Smith Machine Squat', group: 'legs', pattern: 'squat', role: 'main', equip: 'machine', level: 2,
    muscles: 'Quads, glutes',
    how: 'Bar across your upper back, feet slightly in front of the bar. Sit down and back, then drive straight up.',
    avoid: 'Resting the bar on your neck, or rising onto your toes.',
    start: 'Empty bar.',
    bonusTip: 'Place your feet a little further forward to shift work to your glutes, or closer together to target your quads more.',
  },
  {
    id: 'db_rdl', name: 'Dumbbell Romanian Deadlift', group: 'legs', pattern: 'hinge', role: 'main', equip: 'dumbbell', level: 2,
    muscles: 'Hamstrings, glutes, lower back',
    how: "Soft knees. Push your hips back and slide the dumbbells down your thighs until you feel a hamstring stretch, then squeeze your glutes to stand.",
    avoid: 'Rounding your back. Stop lowering where your flat back ends.',
    start: 'Two 6–10 kg dumbbells.',
    bonusTip: "Think 'hips back', not 'hands down'. The stretch in your hamstrings is where the growth happens, so control the lowering for 3 seconds.",
  },
  {
    id: 'leg_curl', name: 'Seated Leg Curl', group: 'legs', pattern: 'hinge', role: 'accessory', equip: 'machine', level: 1,
    muscles: 'Hamstrings',
    how: 'Pad just above your heels, thigh pad snug. Curl down smoothly, pause, then let it return slowly.',
    avoid: 'Lifting your hips off the seat to swing the weight.',
    start: 'The lightest 2–3 plates on the stack.',
    bonusTip: 'Lean your torso slightly forward while curling. It stretches the hamstrings more and makes the same weight noticeably harder.',
  },
  {
    id: 'leg_extension', name: 'Leg Extension', group: 'legs', pattern: 'squat', role: 'accessory', equip: 'machine', level: 1,
    muscles: 'Quads',
    how: "Knees in line with the machine's pivot. Straighten your legs, squeeze for 1 second at the top, lower slowly.",
    avoid: 'Kicking the weight up with momentum.',
    start: 'The lightest 2–3 plates on the stack.',
    bonusTip: 'Hold the top position for a full 2 seconds on your last set. That squeeze gives a strong quad pump with very little joint stress.',
  },
  {
    id: 'db_lunge', name: 'Dumbbell Walking Lunge', group: 'legs', pattern: 'lunge', role: 'main', equip: 'dumbbell', level: 2,
    muscles: 'Quads, glutes',
    how: 'Dumbbells at your sides. Step forward, lower your back knee toward the floor, then push through the front heel into the next step.',
    avoid: 'Your front knee collapsing inward, or taking tiny steps.',
    start: 'Bodyweight first, then two 4–6 kg dumbbells.',
    bonusTip: 'Take a slightly longer stride and lean your torso forward a little to put more work into your glutes.',
  },
  {
    id: 'hip_thrust', name: 'Barbell Hip Thrust', group: 'legs', pattern: 'hinge', role: 'main', equip: 'barbell', level: 2,
    muscles: 'Glutes, hamstrings',
    how: 'Upper back on a bench, padded bar across your hips. Drive your hips up until your body is flat from shoulders to knees, pause, lower.',
    avoid: 'Arching your lower back at the top. Keep your chin tucked and ribs down.',
    start: 'Empty bar with a pad.',
    bonusTip: 'Pause for 2 seconds at the top of each rep and squeeze your glutes hard. Tension at the top is what makes this exercise work.',
  },

  // ───────────── PUSH ─────────────
  {
    id: 'chest_press', name: 'Chest Press Machine', group: 'push', pattern: 'hpush', role: 'main', equip: 'machine', level: 1,
    muscles: 'Chest, front shoulders, triceps',
    how: 'Handles at mid-chest height. Press forward without locking your elbows, then return slowly until you feel a chest stretch.',
    avoid: 'Shoulders rolling forward off the pad.',
    start: '10–20 kg on the stack.',
    bonusTip: 'Pinch your shoulder blades together before the first rep and keep them there. Your chest does more of the work and your shoulders stay safer.',
  },
  {
    id: 'db_bench', name: 'Dumbbell Bench Press', group: 'push', pattern: 'hpush', role: 'main', equip: 'dumbbell', level: 2,
    muscles: 'Chest, triceps, front shoulders',
    how: 'Lie on a flat bench, dumbbells above your chest. Lower to chest level with elbows at about 45°, then press up.',
    avoid: 'Flaring your elbows straight out to the sides.',
    start: 'Two 5–8 kg dumbbells.',
    bonusTip: 'Let the dumbbells go slightly deeper than a barbell would allow. That extra stretch at the bottom is a big driver of chest growth.',
  },
  {
    id: 'incline_db', name: 'Incline Dumbbell Press', group: 'push', pattern: 'hpush', role: 'main', equip: 'dumbbell', level: 2,
    muscles: 'Upper chest, front shoulders',
    how: 'Bench at a low incline (about 30°). Lower the dumbbells to upper-chest level, press up and slightly together.',
    avoid: 'Setting the bench too steep, which turns it into a shoulder press.',
    start: 'Two 4–7 kg dumbbells.',
    bonusTip: 'Keep the incline low, around 30°. It targets the upper chest better than steeper angles, which shift the work to your shoulders.',
  },
  {
    id: 'pec_deck', name: 'Pec Deck Fly', group: 'push', pattern: 'hpush', role: 'accessory', equip: 'machine', level: 1,
    muscles: 'Chest',
    how: 'Handles at chest height, slight bend in your elbows. Bring your arms together in a hugging arc, squeeze, return slowly.',
    avoid: 'Letting the handles pull your arms far behind your body.',
    start: 'The lightest 2–3 plates on the stack.',
    bonusTip: 'Squeeze for 1 second where the handles meet, as if pushing your biceps together. That peak squeeze is what makes flies effective.',
  },
  {
    id: 'machine_shoulder', name: 'Shoulder Press Machine', group: 'push', pattern: 'vpush', role: 'main', equip: 'machine', level: 1,
    muscles: 'Shoulders, triceps',
    how: 'Handles at shoulder level. Press overhead without shrugging, lower with control.',
    avoid: 'Arching your back off the pad.',
    start: '5–15 kg on the stack.',
    bonusTip: 'Stop just short of locking out at the top. Keeping constant tension on your shoulders works them harder than resting at the top.',
  },
  {
    id: 'db_shoulder', name: 'Seated Dumbbell Shoulder Press', group: 'push', pattern: 'vpush', role: 'main', equip: 'dumbbell', level: 1,
    muscles: 'Shoulders, triceps',
    how: 'Sit upright with back support. Press the dumbbells overhead, lower to ear level.',
    avoid: 'The dumbbells drifting forward in front of your face.',
    start: 'Two 4–6 kg dumbbells.',
    bonusTip: "Turn your palms slightly inward, around 30°. It's easier on the shoulder joint and usually lets you press more weight with good form.",
  },
  {
    id: 'lateral_raise', name: 'Dumbbell Lateral Raise', group: 'push', pattern: 'vpush', role: 'accessory', equip: 'dumbbell', level: 1,
    muscles: 'Side shoulders',
    how: 'Slight bend in your elbows. Raise your arms out to the sides up to shoulder height, lower slowly.',
    avoid: 'Swinging. If you need momentum, the weight is too heavy.',
    start: 'Two 2–4 kg dumbbells. Lighter than you think.',
    bonusTip: 'Lead with your elbows, not your hands, and lean forward slightly. This isolates the side shoulder, which gives you wider-looking shoulders.',
  },
  {
    id: 'triceps_pushdown', name: 'Cable Triceps Pushdown', group: 'push', pattern: 'arms', role: 'accessory', equip: 'cable', level: 1,
    muscles: 'Triceps',
    how: 'Elbows pinned to your sides. Push the bar or rope down until your arms are straight, return until your forearms are just above parallel.',
    avoid: 'Elbows drifting forward, or leaning your bodyweight onto the bar.',
    start: '10–15 kg on the stack.',
    bonusTip: 'Use the rope and spread it apart at the bottom. The extra squeeze fully contracts the triceps.',
  },

  // ───────────── PULL ─────────────
  {
    id: 'lat_pulldown', name: 'Lat Pulldown', group: 'pull', pattern: 'vpull', role: 'main', equip: 'cable', level: 1,
    muscles: 'Lats, biceps',
    how: 'Grip a little wider than shoulders. Pull the bar to your upper chest by driving your elbows down, return slowly to a full stretch.',
    avoid: 'Leaning far back or pulling the bar behind your neck.',
    start: '15–25 kg on the stack.',
    bonusTip: "Imagine pulling with your elbows, not your hands. Thinking 'elbows to back pockets' makes your back work instead of your biceps.",
  },
  {
    id: 'assisted_pullup', name: 'Assisted Pull-up Machine', group: 'pull', pattern: 'vpull', role: 'main', equip: 'machine', level: 1,
    muscles: 'Lats, biceps, upper back',
    how: 'Kneel on the pad. Pull your chest toward the bar, then lower all the way down.',
    avoid: 'Too little assistance. More assist weight makes it easier.',
    start: 'High assistance, 30–40 kg.',
    bonusTip: "Reduce the assistance by one plate whenever you hit the top of your rep range on every set. That's your path to an unassisted pull-up.",
  },
  {
    id: 'seated_row', name: 'Seated Cable Row', group: 'pull', pattern: 'hpull', role: 'main', equip: 'cable', level: 1,
    muscles: 'Mid back, lats, biceps',
    how: 'Sit tall, slight knee bend. Pull the handle to your belly button, squeeze your shoulder blades, return with a stretch.',
    avoid: 'Rocking your torso back and forth to move the weight.',
    start: '15–25 kg on the stack.',
    bonusTip: 'Let your shoulder blades stretch forward at the start of each rep, then squeeze them together at the end. The full range builds a thicker back.',
  },
  {
    id: 'machine_row', name: 'Chest-Supported Row Machine', group: 'pull', pattern: 'hpull', role: 'main', equip: 'machine', level: 1,
    muscles: 'Mid back, rear shoulders',
    how: 'Chest on the pad. Pull the handles back until your elbows pass your ribs, pause, return slowly.',
    avoid: 'Shrugging your shoulders up toward your ears.',
    start: '10–20 kg or one plate per side.',
    bonusTip: "Because your chest is supported, you can't cheat. Push close to failure on your final set to get the most from it safely.",
  },
  {
    id: 'db_row', name: 'One-Arm Dumbbell Row', group: 'pull', pattern: 'hpull', role: 'main', equip: 'dumbbell', level: 1,
    muscles: 'Lats, mid back, biceps',
    how: 'One hand and knee on a bench. Pull the dumbbell toward your hip, lower with a stretch.',
    avoid: 'Twisting your torso to heave the weight up.',
    start: 'One 8–12 kg dumbbell.',
    bonusTip: 'Pull toward your hip in an arc rather than straight up. This targets your lats more than your upper back.',
  },
  {
    id: 'face_pull', name: 'Cable Face Pull', group: 'pull', pattern: 'hpull', role: 'accessory', equip: 'cable', level: 1,
    muscles: 'Rear shoulders, upper back',
    how: 'Rope at upper-chest height. Pull toward your face, separating the rope ends and rotating your hands back.',
    avoid: 'Using so much weight that you lean back to pull it.',
    start: '5–10 kg on the stack.',
    bonusTip: 'Finish each rep with your hands beside your ears, like a double-biceps pose. It builds rear shoulders and helps posture after desk work.',
  },
  {
    id: 'db_curl', name: 'Dumbbell Biceps Curl', group: 'pull', pattern: 'arms', role: 'accessory', equip: 'dumbbell', level: 1,
    muscles: 'Biceps',
    how: 'Stand tall, elbows at your sides. Curl the dumbbells up while turning your palms up, lower slowly.',
    avoid: 'Swinging your body or letting your elbows drift forward.',
    start: 'Two 4–6 kg dumbbells.',
    bonusTip: 'Lower each rep over 3 seconds. Most beginners drop the weight quickly and miss half the benefit.',
  },
  {
    id: 'hammer_curl', name: 'Hammer Curl', group: 'pull', pattern: 'arms', role: 'accessory', equip: 'dumbbell', level: 1,
    muscles: 'Biceps, forearms',
    how: 'Palms facing each other throughout. Curl up, pause, lower slowly.',
    avoid: 'Rocking your torso to swing the weight.',
    start: 'Two 4–6 kg dumbbells.',
    bonusTip: 'Hammer curls work the muscle underneath the biceps, which makes your arms look thicker from the front.',
  },

  // ───────────── BODYWEIGHT FALLBACKS (ported from the vanilla version) ─────────────
  {
    id: 'box_squat', name: 'Bench Box Squat', group: 'legs', pattern: 'squat', role: 'main', equip: 'bodyweight', level: 1,
    muscles: 'Quads, glutes',
    how: 'Stand in front of a bench. Sit back until you lightly touch it, then stand up without rocking.',
    avoid: 'Flopping onto the bench — aim for a light tap and stand straight back up.',
    start: 'Bodyweight only. Add a dumbbell held at your chest once 15 reps feel easy.',
    bonusTip: 'Reach your arms straight out in front as you sit back. It counterbalances your weight and keeps your torso more upright.',
  },
  {
    id: 'split_squat', name: 'Split Squat', group: 'legs', pattern: 'squat', role: 'accessory', equip: 'bodyweight', level: 2,
    muscles: 'Quads, glutes',
    how: 'One foot forward, one back. Drop your back knee straight down, then push up through the front heel.',
    avoid: 'Letting the front knee collapse inward.',
    start: 'Hold a wall or rack for balance at first; add dumbbells once steady.',
    bonusTip: 'Keep most of your weight on the front heel, not your toes. It shifts more work onto your glutes and protects your front knee.',
  },
  {
    id: 'glute_bridge', name: 'Glute Bridge', group: 'legs', pattern: 'hinge', role: 'main', equip: 'bodyweight', level: 1,
    muscles: 'Glutes, hamstrings',
    how: 'Lie on your back, knees bent, feet flat. Squeeze your glutes to lift your hips into a straight line, pause 1 second.',
    avoid: 'Arching your lower back at the top — keep your ribs down.',
    start: 'Bodyweight. Rest a dumbbell across your hips once it feels easy.',
    bonusTip: 'Pause 2 full seconds at the top of every rep. Bodyweight only gets harder if you add time under tension, not just reps.',
  },
  {
    id: 'incline_pushup', name: 'Incline Push-up', group: 'push', pattern: 'hpush', role: 'main', equip: 'bodyweight', level: 1,
    muscles: 'Chest, triceps',
    how: 'Hands on a bench or bar, body in a straight line. Lower your chest to the edge, then push away.',
    avoid: 'Letting your hips sag toward the floor.',
    start: 'Use a higher surface to start; lower the surface as you get stronger.',
    bonusTip: "Move to a lower surface (or the floor) as soon as 15 clean reps feel easy — that's the bodyweight version of adding weight.",
  },
  {
    id: 'pike_pushup', name: 'Wall Shoulder Tap Hold', group: 'push', pattern: 'vpush', role: 'main', equip: 'bodyweight', level: 1,
    muscles: 'Shoulders, core',
    how: 'Hands on a wall at shoulder height, step back. Lean in and press away, keeping elbows at about 45°.',
    avoid: 'Letting your head drop forward as you lean in.',
    start: 'Bodyweight. Step farther from the wall to make it harder.',
    bonusTip: "Step your feet back an inch at a time. Distance from the wall is your only 'weight' here, so add it gradually.",
  },
  {
    id: 'prone_y', name: 'Prone Y-Raise', group: 'pull', pattern: 'vpull', role: 'main', equip: 'bodyweight', level: 1,
    muscles: 'Upper back, rear shoulders',
    how: 'Lie face-down, arms overhead in a Y shape. Lift your arms by squeezing your shoulder blades, pause, lower.',
    avoid: 'Lifting with your neck — keep your eyes on the floor.',
    start: 'Bodyweight. Very light plates in each hand once easy.',
    bonusTip: 'Squeeze your shoulder blades together before your arms even move. That\'s the muscle this exercise is training.',
  },
  {
    id: 'snow_angel', name: 'Reverse Snow Angel', group: 'pull', pattern: 'hpull', role: 'main', equip: 'bodyweight', level: 1,
    muscles: 'Upper back',
    how: 'Lie face-down, arms at your sides. Lift your arms slightly and sweep them overhead and back, like a snow angel.',
    avoid: 'Rushing the movement — slow and controlled is the point.',
    start: 'Bodyweight.',
    bonusTip: 'Keep your chin gently tucked throughout. It stops your neck from doing the work your upper back should be doing.',
  },
]

export const BY_ID: Record<string, Exercise> = Object.fromEntries(EXERCISES.map((e) => [e.id, e]))
